//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.27 at 10:41:24 AM EDT 
//


package com.mosaicatm.fuser.airport;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AdaptationAirportsAirportTimezone_QNAME = new QName("", "Timezone");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Adaptation }
     * 
     */
    public Adaptation createAdaptation() {
        return new Adaptation();
    }

    /**
     * Create an instance of {@link Adaptation.Airports }
     * 
     */
    public Adaptation.Airports createAdaptationAirports() {
        return new Adaptation.Airports();
    }

    /**
     * Create an instance of {@link Adaptation.Airports.Airport }
     * 
     */
    public Adaptation.Airports.Airport createAdaptationAirportsAirport() {
        return new Adaptation.Airports.Airport();
    }

    /**
     * Create an instance of {@link Adaptation.Airports.Airport.Timezone }
     * 
     */
    public Adaptation.Airports.Airport.Timezone createAdaptationAirportsAirportTimezone() {
        return new Adaptation.Airports.Airport.Timezone();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Adaptation.Airports.Airport.Timezone }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Timezone", scope = Adaptation.Airports.Airport.class)
    public JAXBElement<Adaptation.Airports.Airport.Timezone> createAdaptationAirportsAirportTimezone(Adaptation.Airports.Airport.Timezone value) {
        return new JAXBElement<Adaptation.Airports.Airport.Timezone>(_AdaptationAirportsAirportTimezone_QNAME, Adaptation.Airports.Airport.Timezone.class, Adaptation.Airports.Airport.class, value);
    }

}
